#!/bin/bash

# BUCLE INFINITO
    while :; do
# LIMPIAR PANTALLA
    clear

 # MENU
    echo ===== FECHA/HORA =====
    echo
    echo '1) Mostrar Hora'
    echo '2) Mostrar Fecha'
    echo '3) Salir'

 # LEA SOLO EL PRIMER CARACTER ESCRITO
    read -n1 -p 'Opcion: ' opc
    echo

 # COMPROBAR EL VALOR ALMACENADO EN 'OPC' Y
 # EJECUTAR EL BLOQUE DE REFERENCIA
    case $opc in
        1)  printf 'Hora: %(%H:%M:%S)T\n';;
        2)  printf 'Data: %(%d/%m/%Y)T\n';;
        3)  break;; # ROMPE EL BUCLE Y FINALIZA LA VIZUALISACION DEL MENU
        *)  echo 'OPCION INVALIDA !!'
    esac

    read -p 'Pressione cualquer tecla para volver...'
done

echo 'Saliendo...'
