#!/bin/bash
#colores
lor1='\033[1;31m';lor2='\033[1;32m';lor3='\033[1;33m';lor4='\033[1;34m';lor5='\033[1;35m';lor6='\033[1;36m';lor7='\033[1;37m'
#IP=$(wget -qO- whatismyip.akamai.com)
#[[ "$IP" = "" ]]&& IP="errorp"
#PASS=$(wget -qO- https://www.dropbox.com/s/q9n4rv3er9mjvtz/listip |grep "$IP" |awk -F : {'print $1'})
#rm -rf instalador.sh
#if [ "$IP" = "$PASS" ]; then
#clear
#else
#echo -e "${lor4}***********************************${lor7}"
#echo -e
#echo -e "\033[97m    ◆ ACCESO NO AUTORIZADO
#echo -e "\033[97m    ◆ TELEGRAM: 
#echo -e "\033[97m    ◆ WHATSAPP: 
#echo -e
#echo -e "${lor4}***********************************${lor7}"
#for pid in $(pgrep python);do
#kill $pid
#done
#1exit
#exit 0
#fi
if [ $(id -u) -eq 0 ];then
clear
else
echo -e "Run the script as user${lor2}root${lor7}"
exit
fi 
#[ -f /usr/bin/vps-mx ]&&echo -e "${lor1}THIRD PARTY SCRIPT DETECTED"&& exit
#[ -f /usr/bin/adm ]&&echo -e "${lor1}THIRD PARTY SCRIPT DETECTED"&& exit 
#[ -f /bin/menu ]&&echo -e "${lor1}THIRD PARTY SCRIPT DETECTED"&& exit 
#[ -f /etc/newadm/menu ]&&echo -e "${lor1}THIRD PARTY SCRIPT DETECTED"&& exit 
fun_bar () {
          comando[0]="$1"
          comando[1]="$2"
          (
          [[ -e $HOME/fim ]] && rm $HOME/fim
          ${comando[0]} > /dev/null 2>&1
          ${comando[1]} > /dev/null 2>&1
          touch $HOME/fim
          ) > /dev/null 2>&1 &
          tput civis
		  echo -e "${lor7}---------------------------------------------------${lor7}"
          echo -ne "${lor7}    WAIT..${lor1}["
          while true; do
          for((i=0; i<18; i++)); do
          echo -ne "${lor5}#"
          sleep 0.2s
          done
         [[ -e $HOME/fim ]] && rm $HOME/fim && break
         echo -e "${col5}"
         sleep 1s
         tput cuu1
         tput dl1
         echo -ne "${lor7}    WAIT..${lor1}["
         done
         echo -e "${lor1}]${lor7} -${lor7} FINISHED ${lor7}"
         tput cnorm
		 echo -e "${lor7}---------------------------------------------------${lor7}"
        }
b="++++++___           _              _ _ _ 
+++++/ _ \_ __ ___ | |_ ___   /\ /(_) | |
++++/ /_)  ' _ \|  _ \ / //_/ | | |
+++/ ___/| | | (_|| (_) / __ \| | | |
+++\/    |_|  \___/ \__\___/\/  \/|_|_|_|"

espe () {   
echo -e "${lor7}"
read -p " Enter to Continue.."
}  
while true; do
clear&&clear
cd /root/ 
if netstat -nltp|grep 'badvpn-udpgw' > /dev/null; then
badudp=$(netstat -nplt |grep 'badvpn-udpgw' | awk -F ":" {'print $2'} | cut -d " " -f 1 | xargs)
else
badudp=$(echo -e "${lor1}not available")
fi 
if netstat -nltp|grep 'dropbear' > /dev/null; then
drobp=$(netstat -nplt |grep 'dropbear' | awk -F ":" {'print $2'} | cut -d " " -f 1 | xargs)
else
drobp=$(echo -e "${lor1}not available")
fi 
if netstat -nltp|grep 'python' > /dev/null; then
pyho=$(netstat -nplt |grep 'python' | awk -F ":" {'print $2'} | cut -d " " -f 1 | xargs)
else
pyho=$(echo -e "${lor1}not available")
fi  
if netstat -nltp|grep 'stunnel4' > /dev/null; then
ssl=$(netstat -nplt |grep 'stunnel4' | awk -F ":" {'print $2'} | cut -d " " -f 1 | xargs)
else
ssl=$(echo -e "${lor1}not available")
fi 
if ps x | grep -w dns-server | grep -v grep 1>/dev/null 2>/dev/null; then 
slowdnsser=$(echo -e "${lor2}ON")
else
slowdnsser=$(echo -e "${lor1}OFF")
fi
if netstat -nltp|grep 'v2raypro' > /dev/null; then
v2ra=$(netstat -nplt |grep 'v2raypro' | awk -F ":::" {'print $2'} | cut -d " " -f 1 | xargs)
else
v2ra=$(echo -e "${lor1}OFF ")
fi

echo -e "${lor4}***************************************************${lor7}"
echo -e "${lor2}   SCRIPT |${lor7} 🌀ADM-WOLI 🌀    "
echo -e "${lor1}===================================================${lor7} "
echo -e "${lor4}$b ${lor7}"
echo -e "${lor7}      Mini Script Panel created by @KillShito "
echo -e "${lor1}[-]———————————————————${lor5}—————————${lor1}——————————————————[-]${lor7}"
echo -e "${lor6}   BADVPN:${lor7} $badudp ${lor5}| ${lor6}SLOWDNS: $slowdnsser ${lor5}| ${lor6}V2RAY:${lor7} ${v2ra} "
echo -e "${lor6}   DROPBEAR:${lor7} $drobp "
echo -e "${lor6}   PYTHON:${lor7} $pyho  "
echo -e "${lor6}   SSL:${lor7}    $ssl "
echo -e "${lor1}[-]———————————————————${lor5}—————————${lor1}——————————————————[-]${lor7}"
echo -e "${lor7}[${lor2}1${lor7}] ${lor3}==>${lor7} SEE SSH CONNECTORS "
echo -e "${lor7}[${lor2}2${lor7}] ${lor3}==>${lor7} USER RECORDS  "
echo -e "${lor7}[${lor2}3${lor7}] ${lor3}==>${lor7} SYSTEM INFORMATION "
echo -e "${lor7}[${lor2}4${lor7}] ${lor3}==>${lor7} ADD / REMOVE / RENEW USERS"
echo -e "${lor7}-----------------${lor2}PROTOCOLS & TOOLS${lor7}-----------------${lor7}"
echo -e "${lor7}[${lor2}5${lor7}] ${lor3}==>${lor7} INSTALL PROTOCOLS "
echo -e "${lor7}[${lor2}6${lor7}] ${lor3}==>${lor7} MORE TOOLS "
echo -e "${lor7}-----------------------${lor2}EXTRAS${lor7}----------------------${lor7}"
echo -e "${lor7}[${lor2}7${lor7}] ${lor3}==>${lor7} CREDITS "
echo -e "${lor7}[${lor2}8${lor7}] ${lor3}==>${lor7} EXIT THE PANEL "
echo -e "${lor1}[-]——————————————————————————————————————————————[-]${lor7}"
unset opc
while [[ -z ${opc} ]]; do	
read -p "SELECT OPTION :" opc
tput cuu1
tput dl1
done
