#!/bin/bash

# Initialize an array with menu options. 
options =( 'Display time.'  'Display date.'  'Exit.' )

# clear the screen
clear

# Menu 
echo  ===== DATE/TIME ===== 
echo

# List the elements contained in 'options'. 
select opc in "${options[@]}" ; of

    # Check the value stored in 'opc' and 
    # execute the referring block.

    # The literal text of the option is stored in each vector in 'opc' and it is 
    # through which the validation is performed. 
    # 
    # Example: 
    # ${options[0]} = Display time. 
    # ${options[1]} = Display date. 
    # ${options[2]} = Exit. 
    # 
    case  $opc in
         ${ options [0] } )    printf  'Time: %(%H:%M:%S)T\n' ;;
        ${ options [1] } )    printf  'Date: %(%d/%m/%Y)T\n' ;;
        ${ options [2] } )    break ;; # End the select. 
        *)   echo  'INVALID OPTION !!' 
    exit

    read -p 'Press any key to go back...' 
done

echo  'Leaving...'
