#!/bin/bash

# INICIALLIZAR UNA MATRIZ CON OPCIONES DE MENU
      options =( 'Display time.'  'Display date.'  'Exit.' )

# ACLARAR/LIMPIAR LA PANTALLA
     clear

# Menu 
      echo  ===== FECHA/HORA ===== 
      echo

# ENUMERE LOS ELEMENTOS CONTENIDOS EN 'OPCIONES' 
      select opc in "${options[@]}" ; of 
# COMPROBAR EL VALOR ALMACENADO EN 'OPC' Y
# EJECUTAR EL BLOQUE DE REFERENCIA

# EL TEXTO LITERALDE LA OPCION SE ALMACENA EN CADA VECTOR EN 'opc' Y ES
# A TRAVEZ DE LA CUAL SE REALIZA LA VALIDACION.

# Example: 
# ${OPCIONES[0]} = MOSTRAR HORA. 
# ${OPCIONES[1]} = MOSTRAR FECHA. 
# ${OPCIONES[2]} = SALIR. 
# 
         case  $opc in
         ${ options [0] } )    printf  'Time: %(%H:%M:%S)T\n' ;;
        ${ options [1] } )    printf  'Date: %(%d/%m/%Y)T\n' ;;
        ${ options [2] } )    break ;; # End the select. 
        *)   echo  'INVALID OPTION !!' 
        exit

        read -p 'Presione enter para volver...' 
done

echo  'Saliendo...'
