#!/bin/bash

# Loop infinito.
while :; do
    # limpa a tela
    clear

    # Menu
    echo ===== DATA/HORA =====
    echo
    echo '1) Exibir hora.'
    echo '2) Exibir data.'
    echo '3) Sair.'

    # Lê somente o primeiro caractere digitado.
    read -n1 -p 'Opção: ' opc
    echo

    # Verifica o valor armazenado em 'opc' e
    # executa o bloco referente.
    case $opc in
        1)  printf 'Hora: %(%H:%M:%S)T\n';;
        2)  printf 'Data: %(%d/%m/%Y)T\n';;
        3)  break;; # Interrompe o loop e finaliza a exibição do menu.
        *)  echo 'OPÇÃO INVÁLIDA !!'
    esac

    read -p 'Pressione qualquer tecla para voltar...'
done

echo 'Saindo...'
